version: "3.9"

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "5000:80"
    volumes:
      - ./server:/usr/src/app
      - ./website/templates:/usr/src/app/templates
      - ./website/static:/usr/src/app/static/website
      - ./music-generator/output:/usr/src/app/static/midi:ro
  music-generator:
    container_name: music-generator
    build: ./music-generator
    volumes:
      - ./music-generator/output:/usr/src/app/output
